shopping_site/config/routes.rb
Rails.application.routes.draw do
  get 'orders_admin/index'
  get 'orders_admin/show'
  patch 'orders_admin/update'
  get 'users_session/new'
  post 'users_session/create'
  get 'users_session/destroy'
  resources :users
  get 'admins_session/new'
  post'admins_session/create'
  get 'admins_session/destroy'
  get 'session/new'
  root 'static#home'
  get 'static/home'
  get 'orders/create'
  
  
  resources :carts, only: [:create, :index, :destroy]
  resources :admins
  resources :items
  resources :orders, only: [:show, :new]
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

shopping_site/app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :item
    validates :user_id, presence: true
    validates :item_id, presence: true
    
end

shopping_site/app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def index
        if logged_in_as_user?
            if session[:item_id].nil?
                @carts = Cart.where(user_id: session[:user_id]).where(status: 0)
            else
                @cart = Cart.new(user_id: session[:user_id], item_id: session[:item_id])
                session.delete(:item_id)
                if @cart.save
                    flash[:success] = 'カートに追加しました'
                    redirect_to carts_url
                else
                    flash[:warning] = 'カートに追加できませんでした'
                    redirect_to root_url
                end
            end
        else
            store_location
            redirect_to users_session_new_url
        end
    end

    def create
        if logged_in_as_user?
            @cart = Cart.new(user_id: session[:user_id], item_id: params[:item_id])
            store_location
            if @cart.save
                flash[:success] = 'カートに追加しました'
                redirect_back_or(root_url)
            else
                flash[:warning] = 'カートに追加できませんでした'
                redirect_back_or(root_url)
            end
        else
            store_location
            session[:item_id] = params[:item_id]
            redirect_to users_session_new_url
        end
    end

    def destroy
        @cart = Cart.find(params[:id])
        flash[:success] = "カートから#{@cart.item.name}は削除されました"
        @cart.destroy
        redirect_to carts_url
    end
    
end

shopping_site/app/helpers/carts_helper.rb
module CartsHelper
end

shopping_site/app/views/carts/index.html.erb
<%= render 'shared/user_nav' %>
<%= render 'shared/success' %>
<% if !@carts.empty? %>
<div class="container">
    <div class="row">
        <div class="col-md-9 mx-auto">
        <h2 class="mt-5 mb-3">ショッピングカート</h2>
        <% sum = 0 %>
        <% @carts.each do |cart| %>
            <div class="card mb-3" style="max-width: 540px">
                <div class="row no-gutters">
                    <div class="col-md-3 my-auto">
                        <%= link_to (image_tag cart.item.image.url, class: "card-img" if cart.item.image?), item_path(cart.item) %>
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <h5 class="card-title"><%= cart.item.name %></h5>
                            <p><%= link_to "削除", cart_path(cart), method: :delete %></p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card-body">
                            <p>¥ <%= cart.item.price.to_s(:delimited) %></p>
                        </div>
                    </div>
                </div>
            </div>
            <% sum = sum + cart.item.price %>
        <% end %>
        <h2>合計金額 : ¥ <%= sum.to_s(:delimited) %></h2>
        </div>
        <div class="col-md-3 my-auto mx-auto">
            <%= form_with(url: new_order_path, method: :get, local: true) do |form| %>
                <div class="actions">
                    <%= form.submit value: "注文する", class: "btn btn-primary" %>
                </div>
            <% end %>
        </div>
        <div class="ml-3 mt-2">
            <%= render 'shared/to_home' %>
        </div>
    </div>
</div>
<% else %>
<div class="container">
    <div class="row">
        <span class="mx-auto mt-5" style="font-size: 3rem">まだカートは空です<span>
    </div>
    <div class="row">
        <div class="col-md-6 mx-auto mt-5">
            <%= render 'shared/to_home' %>
        </div>
    </div>
</div>
<% end %>