shopping_site/config/routes.rb
Rails.application.routes.draw do
  get 'orders_admin/index'
  get 'orders_admin/show'
  patch 'orders_admin/update'
  get 'users_session/new'
  post 'users_session/create'
  get 'users_session/destroy'
  resources :users
  get 'admins_session/new'
  post'admins_session/create'
  get 'admins_session/destroy'
  get 'session/new'
  root 'static#home'
  get 'static/home'
  get 'orders/create'
  
  
  resources :carts, only: [:create, :index, :destroy]
  resources :admins
  resources :items
  resources :orders, only: [:show, :new]
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

shopping_site/app/models/item.rb
class Item < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :name, presence: true, uniqueness: true
    validates :price, presence: true
    has_many :carts, dependent: :destroy
    has_many :items, through: :carts
    has_many :order_pairs
    has_many :orders, through: :order_pairs

    def self.search_by_name(search)
        if search.nil?
            return Item.all
        else 
            return Item.where("UPPER(name) LIKE ?", "%#{search.upcase}%")
        end
    end

    def self.search_order_by_item_name(search)
        items = Item.where("UPPER(name) LIKE ?", "%#{search.upcase}%")
        if items.nil?
            return nil
        else
            return items
        end
    end
end

shopping_site/app/controllers/items_controller.rb
class ItemsController < ApplicationController
        #before_action :set_admin, only: [:show, :edit, :update, :destroy]
        before_action :admin?, only: [:index, :new, :create, :destroy, :edit, :update]

        # GET /admins
        # GET /admins.json
        def index
            items = Item.search_by_name(params[:search])
            @search_word = params[:search]
            if params[:sort].nil?
                @items = items.order(updated_at: "DESC").page(params[:page]).per(10)
            else
                if params[:sort] == "1"
                    @items = items.order(created_at: "DESC").page(params[:page]).per(10)
                elsif params[:sort] == "2"
                    @items = items.order(created_at: "ASC").page(params[:page]).per(10)
                elsif params[:sort] == "3"
                    @items = items.order(name: "ASC").page(params[:page]).per(10)
                elsif params[:sort] == "4"
                    @items = items.order(updated_at: "DESC").page(params[:page]).per(10)
                else
                    @items = items.order(updated_at: "DESC").page(params[:page]).per(10)
                end
            end
        end

        # GET /admins/new
        def new
            @item = Item.new
        end

        def show
            @item = Item.find(params[:id])
        end
        
        def edit
            @item = Item.find(params[:id])
        end

        def update
            @item = Item.find(params[:id])
            if @item.update_attributes(item_params)
                flash[:success] = "商品は正常に更新されました"
                redirect_to items_url
            
            else
                redirect_to edit_item_url, flash: { error: @item.errors.full_messages,
                                                    info: { name: @item.name,
                                                        price: @item.price,
                                                        image: @item.image.url } }
            end
        end
        # POST /admins
        # POST /admins.json
        def create
            @item = Item.new(item_params)
            if @item.save
                flash[:success] = '商品は正常に登録されました' 
                redirect_to items_url
            else
                redirect_to new_item_url, flash: { error: @item.errors.full_messages,
                                                info: { name: @item.name,
                                                        price: @item.price,
                                                        image: @item.image.url } }

            end
        end
        
      
        def destroy
            @item = Item.find(params[:id]).destroy
            redirect_to items_url
            flash[:success] = '商品は正常に削除されました'
        end
      
        private
          # Only allow a list of trusted parameters through.
            def item_params
                params.require(:item).permit(:name, :price, :image)
            end
      
            def admin?
                if session[:admin_id].nil?
                    redirect_to root_url
                elsif Admin.find(session[:admin_id]).nil?
                    redirect_to root_url
                end
            end
end

shopping_site/app/helpers/items_helper.rb
module ItemsHelper
end

shopping_site/app/views/items/_item_form.html.erb
<% if flash[:info].present? %>
<%= form_with(model: item, local: true) do |form| %>
  <%= render 'shared/errors' %>

  <div class="field">
    <%= form.label :name, "商品名", class: "mx-auto" %>
    <%= form.text_field :name, value: flash[:info].fetch("name") ,placeholder: "商品名", class: "form-control mb-2" %>
  </div>

  <div class="field">
    <%= form.label :price, "価格" %>
    <%= form.number_field :price, value: flash[:info].fetch("price"), placeholder: "価格（円)", class: "form-control mb-2" %>
  </div>

  <div class="custom-file mb-5">
    <%= form.label :image, "商品画像(こちらにドロップすることもできます)", class: "custom-file-label mt-3" %>
    <%= form.file_field :image, value: flash[:info].fetch("image"), class: "custom-file-input mb-3"%>
  </div>


  <div class="actions mx-auto">
    <%= form.submit value: "商品を登録", class: "btn btn-primary mx" %>
  </div>
<% end %>

<% else %>
<%= form_with(model: item, local: true) do |form| %>
  <%= render 'shared/errors' %>

  <div class="field">
    <%= form.label :name, "商品名", class: "mx-auto" %>
    <%= form.text_field :name, placeholder: "商品名", class: "form-control mb-2" %>
  </div>

  <div class="field">
    <%= form.label :price, "価格" %>
    <%= form.number_field :price, placeholder: "価格（円)", class: "form-control mb-2" %>
  </div>

  <div class="custom-file mb-5">
    <%= form.label :image, "商品画像(こちらにドロップすることもできます)", class: "custom-file-label mt-3" %>
    <%= form.file_field :image, class: "custom-file-input mb-3"%>
  </div>


  <div class="actions mx-auto">
    <%= form.submit value: "商品を登録", class: "btn btn-primary mx" %>
  </div>
<% end %>
<% end %>

shopping_site/app/views/items/edit.html.erb
<%= render 'shared/admin_nav' %>
<%= render 'shared/success' %>
<div class="containe">
    <div class="row">
        <div class="col-md-6 mx-auto">
        <h2 class="mx-auto mt-2 mb-2">商品編集</h2>
        <%= render 'item_form', item: @item %>
        <div class="mt-4">
        <%= render 'shared/to_items' %>
        </div>
        </div>

    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.js"></script>
<script>
    bsCustomFileInput.init();
</script>

shopping_site/app/views/items/index.html.erb
<%= render 'shared/admin_nav' %>
<%= render 'shared/success' %>
<div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="mx-auto mr-0">
          <%= form_with(url: new_item_path, method: :get, local: true, class: "form-inline mt-4 mb-4") do |form| %>
            <%= form.submit value: "商品を追加", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="float-right mx-auto">
          <%= form_with(url: items_path, method: :get, local: true, class: "form-inline mt-4 mb-4") do |form| %>
            <%= form.text_field :search, value: @search_word, class: "form-control", placeholder: "商品名を入力" %>
            <%= form.submit value: "商品名で検索", class: "btn btn-outline-success" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
        <div class="col-md-12 mx-auto">
          <h2 class="mt-1 mb-3">商品一覧</h2>
          <%= render "shared/admin_sort_items", url: items_path, search_word: @search_word %>
          <% @items.each do |item| %>
              <div class="card mb-3" style="max-width: 100px, width: 100%">
                  <div class="row no-gutters">
                      <div class="col-md-3 my-auto">
                          <%= link_to (image_tag item.image.url, class: "card-img-left" if item.image?), item_path(item) %>
                      </div>
                      <div class="col-md-6">
                          <div class="card-body">
                              <h5 class="card-title"><%= item.name %></h5>
                              <p>価格 : ¥<%= item.price.to_s(:delimited) %></p>
                              <p>最終更新日 : <%= item.updated_at.to_s(:datetime_jp) %></p>
                          </div>
                      </div>
                      <div class="col-md-3">
                          <div class="card-body">
                            <p><%= link_to '削除', item, method: :delete, data: { confirm: '削除してもよろしいですか?' } %></p>
                            <p><%= link_to '編集', edit_item_path(item) %></p>
                          </div>
                      </div>
                  </div>
              </div>
          <% end %>
        </div>
    </div>
    <div class="row">
      <div class="mx-auto">
        <%= paginate @items %>
      </div>
    </div>
    <div class="row">
      <div class="mb-3 float-left">
        <%= render 'shared/to_admins' %>
      </div>
    </div>
</div>

shopping_site/app/views/items/new.html.erb
<%= render 'shared/admin_nav' %>
<%= render 'shared/success' %>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
        <h2 class="mx-auto mt-2 mb-2">商品追加</h2>
        <%= render 'item_form', item: @item %>
        <div class="mt-4">
        <%= render 'shared/to_items' %>
        </div>
        </div>

    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.js"></script>
<script>
    bsCustomFileInput.init();
</script>

shopping_site/app/views/items/show.html.erb
<%= render 'shared/user_nav' %>
<%= render 'shared/success' %>
<div class="container">
    <div class="row ml-5 mt-5">
        <div class="col-md-6 mx-auto">
            <%= image_tag @item.image.url, class: "item-show-img mt-5" if @item.image? %>
            <div class="mt-5">
                <%= render 'shared/to_home' %>
            </div>
        </div>
        <div class="col-md-6 mx-auto">
            <p class="mx-auto mt-5" style="font-size: 4rem;"><%= @item.name %></p>
            <p class="mx-auto mt-5" style="color: red; font-size: 1.5rem;">
                <span style="color: gray;">価格 : </span>
                ¥<%= @item.price.to_s(:delimited) %>
            </p>
            <%= form_with(url: carts_path, local: true) do |form| %>
                <div class="field">
                    <%= form.hidden_field :item_id, value: @item.id %>
                </div>
                <div class="actions mt-5">
                    <%= form.submit value: "カートに追加", class: "btn btn-primary" %>
                </div>
            <% end %>
        </div>
    </div>
</div>