shopping_site/config/routes.rb
Rails.application.routes.draw do
  get 'orders_admin/index'
  get 'orders_admin/show'
  patch 'orders_admin/update'
  get 'users_session/new'
  post 'users_session/create'
  get 'users_session/destroy'
  resources :users
  get 'admins_session/new'
  post'admins_session/create'
  get 'admins_session/destroy'
  get 'session/new'
  root 'static#home'
  get 'static/home'
  get 'orders/create'
  
  
  resources :carts, only: [:create, :index, :destroy]
  resources :admins
  resources :items
  resources :orders, only: [:show, :new]
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

shopping_site/app/controllers/orders_admin_controller.rb
class OrdersAdminController < ApplicationController
  before_action :admin?
  def index
    @search_word = params[:search]
    if @search_word.nil?
      @orders = Order.order(created_at: "DESC").page(params[:page]).per(5)
    elsif @search_word.empty?
      @orders = Order.order(created_at: "DESC").page(params[:page]).per(5)
    else
      items = Item.search_order_by_item_name(@search_word)
      if items.empty?
        @orders = Order.order(created_at: "DESC").page(params[:page]).per(5)
      else 
        first_item = items.first
        first_orders = first_item.orders
        items.each do |item|
          if item != first_item
            first_orders = first_orders + item.orders
          end
        end
        @orders = Order.where(id: first_orders.map{ |order| order.id }).order(created_at: "DESC").page(params[:page]).per(5)
      end
    end
    @order_count = Order.count
    render 'orders_admin/index'
  end

  def show
    @order = Order.find(params[:order_id])
    render 'orders_admin/show'
  end

  def update
    
    @order = Order.find(params[:order_id])
    status_request_valid?(@order, params[:order_id])
    if ((params[:status] == '1' || params[:status] == '2') && (not params[:status].nil?))
      @order.update_attributes(status: params[:status].to_i)
      flash[:success] = "注文ステータスが更新されました"
      redirect_back(fallback_location: orders_admin_index_path)
    else
      flash[:warning] = "更新に失敗しました"
      redirect_back(fallback_location: orders_admin_index_path)
    end
  end

  private
    def admin?
      
      if session[:admin_id].nil?
        
        redirect_to root_url
      elsif Admin.find(session[:admin_id]).nil?
        redirect_to root_url
      end
    end

    def status_request_valid?(order, status)
      previous_status = order.status
      if previous_status > status.to_i
        redirect_to orders_admin_index_url
      end
    end
end

shopping_site/app/helpers/orders_admin_helper.rb
module OrdersAdminHelper
end

shopping_site/app/views/orders_admin/index.html.erb
<%= render 'shared/admin_nav' %>
<%= render 'shared/success' %>
<div class="container">
  <div class="row">
    <div class="col-md-7 text-left">
      <h2 class="mt-4 mb-4">注文一覧</h2>
    </div>
    <div class="col-md-5 mr-0">
    <%= form_with(url: orders_admin_index_path, method: :get, local: true, class: "form-inline mt-4 mb-4") do |form| %>
      <%= form.text_field :search, placeholder: "注文に含まれる商品名", class: "form-control sm-2" %>
      <%= form.submit value: "注文を検索", class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
    </div>
  </div>
  <div class="row">
    <% @orders.each do |order| %>
        <% if order.items.empty? %>
            <% next %>
        <% end %>
      <div class="card mb-3" style="width: 100%; max-width: 1000px;">
        <div class="card-header">
          <div class="row">
          <div class="col-md-3">
            <p class="exp_text">注文日時</p>
            <p class="exp_text"><%= order.created_at.to_s(:datetime_jp) %></p>
          </div>
          <div class="col-md-3">
            <p class="exp_text">最終更新日時</p>
            <p class="exp_text"><%= order.updated_at.to_s(:datetime_jp) %></p>
          </div>
          <div class="col-md-3">
            <p class="exp_text">合計金額</p>
            <p class="exp_text"><% sum = 0 %><% order.items.each { |item| sum += item.price } %>¥<%= sum.to_s(:delimited) %></p>
          </div>
          <div class="col-md-3 text-right">
            <p class="exp_text">注文ステータス</p>
            <% case order.status %>
                <% when 0 %>
                    <p class="exp_text">入金待ち</p>
                <% when 1 %>
                    <p class="exp_text">発送待ち</p>
                <% when 2 %>
                    <p class="exp_text">発送完了</p>
            <% end %>
          </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 my-auto">
            <%= link_to (image_tag order.items.first.image.url, class: "card-img-left" if order.items.first.image?), order_path(order) %>
          </div>
          <div class="col-md-6">
            <div class="card-body">
              <h4 class="card-title text-truncate"><%= order.items.first.name %>など<%=order.items.count %>点のご注文</h4>
              <p>購入者 : <%= order.user.name %></p>
              <p>メールアドレス : <%= order.user.email %></p>
            </div>
          </div>
          <div class="col-md-3">
            <div class="card-body">
              <%= form_with(url: orders_admin_show_path, method: :get, local: true, class: "float-center") do |form| %>
                <div class="actions">
                    <%= form.hidden_field :order_id, value: order.id %>
                    <%= form.submit value: "注文管理", class:"btn btn-secondary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <%= paginate @orders %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="mb-3">
      <%= render 'shared/to_admins' %>
    </div>
  </div>
</div>

shopping_site/app/views/orders_admin/show.html.erb
<%= render 'shared/admin_nav' %>
<%= render 'shared/success' %>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="mt-5 mb-2">注文の詳細</h2>
            <div class="card mb-3" style="width: 100%">
                <div class="row no-gutters">
                    <div class="col-md-6 my-auto">
                        <p class="my-auto font-weight-bold">ご注文者情報</p>
                        <p class="my-auto">ご注文者氏名 : <%= @order.user.name %></p>
                        <p class="my-auto">メールアドレス : <%= @order.user.email %></p>
                        <p class="my-auto font-weight-bold">ご注文情報</p>
                        <p class="my-auto">ご購入日 : <%= @order.created_at.to_s(:datetime_jp) %></p>
                        <p class="my-auto">最終更新日 : <%= @order.updated_at.to_s(:datetime_jp) %></p>
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p>
                                <h4 class="text-center mr-5 ml-5" style="display:inline;">注文点数</h4>
                                <h4 class="text-right" style="display:inline;"><%= @order.items.count %>点</h4>
                            </p>
                            <p>
                                <h3 class="text-center mr-5 ml-5" style="display:inline;">ご請求金額</h3>
                                <h3 class="text-right" style="display:inline;">
                                    <% sum = 0 %><% @order.items.each { |item| sum += item.price } %>¥<%= sum.to_s(:delimited) %>
                                </h3>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <h3 class="mb-2">
                注文処理状況  :   
                <% case @order.status %>
                    <% when 0 %>
                    入金待ち
                    <% when 1 %>
                    発送待ち
                    <% when 2 %>
                    発送完了
                <% end %>
            </h3>
        </div>
        <div class="col-md-12 mb-2">
            <%= form_with(url: orders_admin_update_path(order_id: @order.id), method: :patch, local: true, class: "form-inline") do |form| %>
                <% case @order.status %>
                    <% when 0 %>
                        <%= form.select :status, [ ["発送待ち",1], ["発送完了", 2] ], { prompt: "注文ステータスを選択してください" }, {class: 'custom-select'} %>
                            <div class="actions">
                                <%= form.submit value: "変更する", class: "btn btn-primary ml-2" %>
                            </div>
                    <% when 1 %>
                        <%= form.select :status, [ ["発送完了", 2] ], { prompt: "注文ステータスを選択してください" }, {class: 'custom-select'} %>
                            <div class="actions">
                                <%= form.submit value: "変更する", class: "btn btn-primary ml-2" %>
                            </div>
                    <% when 2 %>
                        <p>ステータスは変更できません。</p>
                        <p>管理者にご連絡ください。</p>
                <% end %>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <% @order.items.each do |item| %>
                <div class="card mb-3" style="width: 100%">
                    <div class="row no-gutters">
                        <div class="col-md-3 my-auto">
                            <%= link_to (image_tag item.image.url, class: "card-img-left" if item.image?), item_path(item) %>
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <h5 class="card-title"><%= item.name %></h5>
                                <p>¥ <%= item.price.to_s(:delimited) %></p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="card-body">
                                <%= render 'shared/to_item', item: item %>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>
<div class="container">
  <div class="row">
    <div class="mb-3 ml-3">
      <%= render 'shared/to_admin_orders' %>
    </div>
  </div>
</div>