shopping_site/config/routes.rb
Rails.application.routes.draw do
  get 'orders_admin/index'
  get 'orders_admin/show'
  patch 'orders_admin/update'
  get 'users_session/new'
  post 'users_session/create'
  get 'users_session/destroy'
  resources :users
  get 'admins_session/new'
  post'admins_session/create'
  get 'admins_session/destroy'
  get 'session/new'
  root 'static#home'
  get 'static/home'
  get 'orders/create'
  
  
  resources :carts, only: [:create, :index, :destroy]
  resources :admins
  resources :items
  resources :orders, only: [:show, :new]
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

shopping_site/app/views/shared/_admin_nav.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-sm">
    <%= link_to "管理者ページ", admins_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav4">
      <ul class="navbar-nav mr-0">
          <li class="nav-item mx-auto">
              <%= link_to "ユーザーぺージ", root_path, class: "nav-link"%>
          </li> 
          <li class="nav-item mx-auto">
              <%= link_to "管理ユーザー", admins_path, class: "nav-link"%>
          </li> 
          <li class="nav-item mx-3 mx-auto">
              <%= link_to "商品管理", items_path, class: "nav-link" %>
          </li>
          <li class="nav-item mx-3 mx-auto">
              <%= link_to "注文管理",  orders_admin_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item mx-3 mx-auto">
              <%= link_to "ログアウト",  admins_session_destroy_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
</nav>

shopping_site/app/views/shared/_admin_sort_items.html.erb
<% #params[:sort]に渡す→存在で場合わけ %>
<div class="form-group my-auto my-lg-0">
<%= form_with(url: url, method: :get, local: true, class: "form-inline my-auto") do |form| %>
    <%= form.select :sort, [ ["新着順",1], ["古い順", 2], ["名前順", 3], ["更新順", 4] ], { prompt: "並び順" }, {class: 'custom-select'} %>
    <%= form.hidden_field :search, value: search_word %>
    <div class="actions">
        <%= form.submit value: "並び替える", class:"my-2 my-sm-0 ml-1 btn btn-outline-secondary" %>
    </div>
<% end %>
</div>

shopping_site/app/views/shared/_errors.html.erb
<% if flash[:error].present? %>
  <div class="alert alert-danger">
    <ul class="errors" style="list-style-type: none;">
      <% flash[:error].each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  </div>
<% end %>

shopping_site/app/views/shared/_sort_items.html.erb
<% #params[:sort]に渡す→存在で場合わけ %>
<div class="form-group my-auto my-lg-0">
<%= form_with(url: url, method: :get, local: true, class: "form-inline my-auto") do |form| %>
    <%= form.select :sort, [ ["新着順",1], ["古い順", 2], ["名前順", 3] ], { prompt: "並び順" }, {class: 'custom-select'} %>
    <%= form.hidden_field :search, value: search_word %>
    <div class="actions">
        <%= form.submit value: "並び替える", class:"my-2 my-sm-0 ml-1 btn btn-outline-secondary" %>
    </div>
<% end %>
</div>

shopping_site/app/views/shared/_success.html.erb
<% if flash[:success].present? %>
  <div class="alert alert-success">
    <p class="text-center"><%= flash[:success] %></p>
  </div>
<% end %>

shopping_site/app/views/shared/_to_admin_orders.html.erb
<%= form_with(url: orders_admin_index_path, method: :get, local: true, class: "float-left") do |form| %>
                <div class="actions">
                    <%= form.submit value: "注文一覧へ戻る", class:"btn btn-secondary" %>
                </div>
<% end %>

shopping_site/app/views/shared/_to_admins.html.erb
<%= form_with(url: admins_path, method: :get, local: true, class: "float-left") do |form| %>
                <div class="actions">
                    <%= form.submit value: "管理者ホームへ戻る", class:"btn btn-secondary" %>
                </div>
<% end %>

shopping_site/app/views/shared/_to_cart.html.erb
<%= form_with(url: carts_path, method: :get, local: true, class: "float-left") do |form| %>
                <div class="actions">
                    <%= form.submit value: "カートへ戻る", class:"btn btn-secondary" %>
                </div>
<% end %>

shopping_site/app/views/shared/_to_item.html.erb
<%= form_with(url: item_url(item), method: :get, local: true, class: "float-center") do |form| %>
                <div class="actions">
                    <%= form.submit value: "商品詳細ページへ", class:"btn btn-secondary" %>
                </div>
<% end %>

shopping_site/app/views/shared/_to_items.html.erb
<%= form_with(url: items_path, method: :get, local: true, class: "float-left") do |form| %>
                <div class="actions">
                    <%= form.submit value: "商品一覧へ戻る", class:"btn btn-secondary" %>
                </div>
<% end %>

shopping_site/app/views/shared/_to_main_page.html.erb
<%= form_with(url: static_home_url, method: :get, local: true, class: "float-center") do |form| %>
                <div class="actions">
                    <%= form.submit value: "ショッピングサイトへ", class:"btn btn-secondary" %>
                </div>
<% end %>

shopping_site/app/views/shared/_to_order_detail.html.erb
<%= form_with(url: order_url(order), method: :get, local: true, class: "float-left") do |form| %>
                <div class="actions">
                    <%= form.submit value: "注文履歴", class:"btn btn-primary" %>
                </div>
<% end %>

shopping_site/app/views/shared/_to_user_orders.html.erb
<%= form_with(url: user_path(user), method: :get, local: true, class: "float-left") do |form| %>
                <div class="actions">
                    <%= form.submit value: "注文一覧へ", class:"btn btn-secondary" %>
                </div>
<% end %>

shopping_site/app/views/shared/_user_nav.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-sm">
    <%= link_to "ショッピングサイト", root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav4">
            <div class="form-inline my-2 my-lg-0  form-group mx-auto">
                <%= form_with(url: static_home_path, method: :get, local: true) do |form| %>
                <%= form.hidden_field :search, value: @search_word %>
                <%= form.text_field :search, value: @search_word, placeholder: "キーワード", class: "form-control sm-2" %>
                <%= form.submit value: "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
                <% end %>
            </div>
            <% if logged_in_as_user? %>
            <ul class="navbar-nav mr-0">
                <li class="nav-item mx-auto">
                    <%= link_to "カートを見る", carts_path, class: "nav-link"%>
                </li> 
                <li class="nav-item mx-3 mx-auto">
                    <%= link_to "注文履歴", user_path(session[:user_id]), class: "nav-link" %>
                </li>
                <li class="nav-item mx-3 mx-auto">
                    <%= link_to "ログアウト",  users_session_destroy_path, class: "nav-link" %>
                </li>
            </ul>
            <% else %>
            <ul class="navbar-nav float-right">
                <li class="nav-item mx-auto">
                    <%= link_to "カートを見る", carts_path, class: "nav-link" %>
                </li>
                <li class="nav-item  mx-3 mx-auto">
                    <%= link_to 'ログイン', users_session_new_path(from_home: 1), class: "nav-link" %>
                </li>  
                <li class="nav-item">
                    <%= link_to "アカウントをお持ちでない方", new_user_path , class: "nav-link"%>
                </li>
            </ul> 
            <% end %>
    </div>
</nav>